### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mpetricek** [retrofuturejosh/react-modular-audio-player#8]
Hi,

I started using your plugin today and it's great! However on the build I'm getting multiple errors.

One of theme is this one:

WebpackError: ReferenceError: window is not defined

I'll provide more info if needed.

Thank you!

**Comment by retrofuturejosh** [comment]
Hey,

Thanks. This plugin is designed to run in browser. It utilizes `window.requestAnimationFrame()` in order to render the scrolling time bar. Your browser should have window defined.

Are you attempting to use server-side rendering? If so, this may help: https://medium.com/@Jense5_/use-document-and-window-with-gatsby-e9a92ee31f36
